### ISSUE TITLE
Fritzing file

### ISSUE THREAD

**Issue by gabrielemaffoni** [sparkfun/ToF_Range_Finder_Breakout-VL6180#1]
Any chance you have the fritzing file for this?
Thank you!

**Comment by bboyho** [comment]
Hmm, it looks like one was created but it was never saved for the public [ [https://github.com/sparkfun/Fritzing_Parts/tree/master/products](https://github.com/sparkfun/Fritzing_Parts/tree/master/products) ] :'(. I'll put it on the queue to see what we can do.

**Comment by santaimpersonator** [comment]
You can also use these great tutorials to create the part as well:
* https://learn.sparkfun.com/tutorials/make-your-own-fritzing-parts/all
* http://fritzing.org/learning/tutorials/creating-custom-parts/

**Comment by bboyho** [comment]
@loricrotser created the part and uploaded into our Fritzing repo @gabrielemaffoni . =) You can find it in our Fritzing repo here => [ [https://github.com/sparkfun/Fritzing_Parts/blob/master/products/12784_sfe_vl6180_breakout.fzpz](https://github.com/sparkfun/Fritzing_Parts/blob/master/products/12784_sfe_vl6180_breakout.fzpz) ].
